name: 'my_dbt_project'
version: '1.1'
config-version: 2

profile: 'dbt_demo'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
analysis-paths: ['analysis']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_modules'

models:
  my_dbt_project:
    +materialized: view         # Por defecto, todo se crea como vista
    staging:
      +schema: stg              # Los modelos en /models/staging irán al schema "stg" (o silver) luego el target es target_stg
    marts: # capa gold
      +schema: marts            # Los modelos en /models/marts irán al schema "marts" (o gold), target_marts

seeds:
  my_dbt_project:
    +schema: raw                # Los seeds van al schema "raw" (los datos ingestados) target_raw
    +column_types:
      order_id: integerdbt
#bigquery db
      #country: string
      #amount: float
#postgres db
      country: text
      amount: numeric
#otro motor db, van a especificar los tipos de datos correspondientes


